# Write your MySQL query statement below

WITH FIRST_LOGIN AS(
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOG
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) 

SELECT 
ROUND(COUNT(DISTINCT A.PLAYER_ID)/COUNT(DISTINCT F.PLAYER_ID),2) AS fraction  

FROM FIRST_LOGIN F
LEFT JOIN ACTIVITY A
ON F.PLAYER_ID = A.PLAYER_ID AND A.EVENT_DATE = DATE_ADD(F.FIRST_LOG, INTERVAL 1 DAY);